import 'package:flutter/material.dart';
import 'responsive.dart';

class AlertDetailsScreen extends StatelessWidget {
  final String title;
  final String device;
  final String time;
  final IconData icon;
  final Color iconColor;

  const AlertDetailsScreen({
    super.key,
    required this.title,
    required this.device,
    required this.time,
    required this.icon,
    required this.iconColor,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FC),

      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,

        title: Text(
          'Alert Details',
          style: TextStyle(
            color: const Color(0xFF1E293B),
            fontSize: Responsive.font(context, 21),
            fontWeight: FontWeight.bold,
          ),
        ),
      ),

      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.symmetric(
            horizontal: Responsive.w(context, 0.05),
            vertical: Responsive.h(context, 0.025),
          ),

          child: Column(
            children: [
              SizedBox(
                height: Responsive.h(context, 0.035),
              ),

              Container(
                width: Responsive.w(context, 0.21),
                height: Responsive.w(context, 0.21),

                decoration: BoxDecoration(
                  color: iconColor.withValues(alpha: 0.12),
                  shape: BoxShape.circle,
                ),

                child: Icon(
                  icon,
                  color: iconColor,
                  size: Responsive.w(context, 0.105),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.025),
              ),

              Text(
                title,
                textAlign: TextAlign.center,
                maxLines: 3,
                overflow: TextOverflow.ellipsis,

                style: TextStyle(
                  fontSize: Responsive.font(context, 22),
                  fontWeight: FontWeight.bold,
                  color: const Color(0xFF1E293B),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.012),
              ),

              Text(
                device,
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: Responsive.font(context, 16),
                  color: const Color(0xFF64748B),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.006),
              ),

              Text(
                time,
                style: TextStyle(
                  fontSize: Responsive.font(context, 13),
                  color: const Color(0xFF94A3B8),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.04),
              ),

              Container(
                width: double.infinity,
                padding: EdgeInsets.all(
                  Responsive.w(context, 0.05),
                ),

                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(
                    Responsive.radius(context, 16),
                  ),

                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.05),
                      blurRadius: Responsive.w(context, 0.025),
                      offset: Offset(
                        0,
                        Responsive.h(context, 0.004),
                      ),
                    ),
                  ],
                ),

                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Alert Information',
                      style: TextStyle(
                        fontSize: Responsive.font(context, 17),
                        fontWeight: FontWeight.bold,
                        color: const Color(0xFF1E293B),
                      ),
                    ),

                    SizedBox(
                      height: Responsive.h(context, 0.018),
                    ),

                    Text(
                      'This alert was generated by your TraceIt device.',
                      style: TextStyle(
                        color: const Color(0xFF64748B),
                        fontSize: Responsive.font(context, 14),
                        height: 1.5,
                      ),
                    ),
                  ],
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.03),
              ),
            ],
          ),
        ),
      ),
    );
  }
}