// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgAEXdR28F-xA7iIS6wW8kdJU9ZMlWbo',
    appId: '1:666103000145:web:30ac8801abb95213a3dc70',
    messagingSenderId: '666103000145',
    projectId: 'trackit-121931',
    authDomain: 'trackit-121931.firebaseapp.com',
    storageBucket: 'trackit-121931.firebasestorage.app',
    measurementId: 'G-4P9L7YGFEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDSS4eYwIe27u2rRjiYGzDU5SXJI0VRE',
    appId: '1:666103000145:android:d64fc285454cb4f6a3dc70',
    messagingSenderId: '666103000145',
    projectId: 'trackit-121931',
    storageBucket: 'trackit-121931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHUHGqF2y0EliqXycZ8wxoFeemAhZEts',
    appId: '1:666103000145:ios:e78a7f28a22a250ca3dc70',
    messagingSenderId: '666103000145',
    projectId: 'trackit-121931',
    storageBucket: 'trackit-121931.firebasestorage.app',
    iosBundleId: 'com.example.traceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDHUHGqF2y0EliqXycZ8wxoFeemAhZEts',
    appId: '1:666103000145:ios:e78a7f28a22a250ca3dc70',
    messagingSenderId: '666103000145',
    projectId: 'trackit-121931',
    storageBucket: 'trackit-121931.firebasestorage.app',
    iosBundleId: 'com.example.traceit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgAEXdR28F-xA7iIS6wW8kdJU9ZMlWbo',
    appId: '1:666103000145:web:37b95f2eacbadf80a3dc70',
    messagingSenderId: '666103000145',
    projectId: 'trackit-121931',
    authDomain: 'trackit-121931.firebaseapp.com',
    storageBucket: 'trackit-121931.firebasestorage.app',
    measurementId: 'G-Y50GS7T8SS',
  );
}
