import 'package:flutter/material.dart';
import '../utils/responsive.dart';

class AlertDetailsScreen extends StatelessWidget {
  final String title;
  final String device;
  final String time;
  final IconData icon;
  final Color iconColor;

  const AlertDetailsScreen({
    super.key,
    required this.title,
    required this.device,
    required this.time,
    required this.icon,
    required this.iconColor,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FC),

      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        title: Text(
          'Alert Details',
          style: TextStyle(
            color: const Color(0xFF1E293B),
            fontSize: Responsive.font(context, 5.5),
            fontWeight: FontWeight.bold,
          ),
        ),
      ),

      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),

          padding: EdgeInsets.all(
            Responsive.w(context, 0.05),
          ),

          child: Column(
            children: [
              SizedBox(
                height: Responsive.h(context, 0.035),
              ),

              Container(
                width: Responsive.w(context, 0.205),
                height: Responsive.w(context, 0.205),

                decoration: BoxDecoration(
                  color: iconColor.withValues(alpha: 0.12),
                  shape: BoxShape.circle,
                ),

                child: Icon(
                  icon,
                  color: iconColor,
                  size: Responsive.w(context, 0.103),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.025),
              ),

              Text(
                title,
                textAlign: TextAlign.center,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,

                style: TextStyle(
                  fontSize: Responsive.font(context, 5.6),
                  fontWeight: FontWeight.bold,
                  color: const Color(0xFF1E293B),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.012),
              ),

              Text(
                device,
                textAlign: TextAlign.center,

                style: TextStyle(
                  fontSize: Responsive.font(context, 4.1),
                  color: const Color(0xFF64748B),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.006),
              ),

              Text(
                time,
                style: TextStyle(
                  fontSize: Responsive.font(context, 3.3),
                  color: const Color(0xFF94A3B8),
                ),
              ),

              SizedBox(
                height: Responsive.h(context, 0.04),
              ),

              Container(
                width: double.infinity,

                padding: EdgeInsets.all(
                  Responsive.w(context, 0.05),
                ),

                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(
                    Responsive.radius(context, 0.04),
                  ),
                ),

                child: Column(
                  crossAxisAlignment:
                      CrossAxisAlignment.start,

                  children: [
                    Text(
                      'Alert Information',
                      style: TextStyle(
                        fontSize:
                            Responsive.font(context, 4.1),
                        fontWeight: FontWeight.bold,
                        color: const Color(0xFF1E293B),
                      ),
                    ),

                    SizedBox(
                      height: Responsive.h(context, 0.018),
                    ),

                    Text(
                      'This alert was generated by your TraceIt device.',
                      style: TextStyle(
                        color: const Color(0xFF64748B),
                        fontSize:
                            Responsive.font(context, 3.6),
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}